### ISSUE TITLE
Not pushing to Heroku

### ISSUE THREAD

**Issue by nfriend21** [SFEley/sinatra-flash#5]
Your gem will not push to heroku on it's own.  It can only push without error by doing:

gem 'sinatra-flash', :git => 'https://github.com/SFEley/sinatra-flash.git'

**Comment by dvidsilva** [comment]
you just saved my life

well, not literally, but i was going crazy finding info about this lol...

is probably because the gem is not in the regular repos, maybe

**Comment by nfriend21** [comment]
possibly...but happy I saved you some time, my friend!
